language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: "landongerrits-github"
    token:
      secure: "5b7b626ff567cd8430d75e92e61f14db637c4316"
jdk:
  - oraclejdk8
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'